trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- script: dotnet restore WebApplication1/WebApplication1.csproj
  displayName: Restore Dependencies

- script: dotnet build WebApplication1/WebApplication1.csproj --configuration $(buildConfiguration)
  displayName: Build Application

- script: dotnet publish WebApplication1/WebApplication1.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish Application

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'project1azure'
    appType: 'webApp'
    appName: 'project1sangram'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'