trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- script: dotnet restore
  displayName: Restore Dependencies

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build Application

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish Application


- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'project1azure'
    command: 'build'